# -*- coding: utf-8 -*-
"""Declarative domain profiles for the visual rhythm director."""
from __future__ import annotations

def _p(theme, shot, interrupt, cards, transitions, sfx, grammar, hook,
       sequence, sound, direction="match subject movement across the cut"):
    return {
        "theme": theme, "shot": shot, "interrupt": interrupt, "cards": cards,
        "transitions": transitions, "sfx": sfx, "grammar": grammar, "hook": hook,
        "sequence": sequence, "sound": sound, "direction": direction,
    }


# domain（怎麼剪）與 theme（長什麼樣）刻意分離。兩者目前一對一居多，但 contract 不綁死。
PROFILES = {
    "ai": _p("ai", (2.2, 5.0), (9.0, 16.0), ("code", "steps", "proof", "question"),
             ("cut", "punch", "screen_wipe"), .34,
             "先秀可驗證結果→真操作→局部放大→錯誤／修正→證據；畫面跟著游標意圖，不追每次點擊",
             "第一鏡先看完成結果或最反直覺的操作",
             (("result", "screen_context", "cursor_action", "proof"),
              ("question", "wrong_way", "correct_way", "before_after")),
             ("clean_click", "keyboard_detail", "subtle_ui_tone")),
    "food": _p("food", (.8, 2.4), (6.0, 10.0), ("price", "taste", "menu", "verdict"),
               ("cut_on_action", "match_cut", "whip"), .50,
               "環境全景→製作動作→極近質地→入口反應；滋滋、切、脆聲優先於 BGM",
               "第一鏡先給牽絲、切面、起鍋或入口反應",
               (("hero_detail", "wide_place", "hand_action", "texture_close", "reaction"),
                ("ingredient", "process", "sizzle", "plate", "verdict")),
               ("sizzle", "knife", "crunch", "room_tone")),
    "travel": _p("travel", (1.4, 4.2), (10.0, 18.0), ("location", "route", "note", "chapter"),
                 ("match_motion", "foreground_wipe", "cut"), .24,
                 "目的地揭露→地標全景→人作比例尺→移動 POV→在地細節；跨地點先用聲音開門",
                 "第一鏡先兌現目的地最值得看的畫面",
                 (("destination_reveal", "establishing", "human_scale", "moving_pov", "detail"),
                  ("map", "departure", "arrival", "local_action", "quiet_observation")),
                 ("location_wild_track", "footstep", "transport", "crowd_bed")),
    "toy": _p("toy", (.8, 2.5), (6.0, 10.0), ("spec", "detail", "score", "question"),
              ("punch", "snap", "cut_on_action"), .54,
              "完成品爆閃→包裝懸念→拆封手部→零件微距→組好旋轉；揭曉後留半拍讓人看清",
              "第一鏡先露完成品一角或最驚喜機關",
              (("finished_tease", "package", "seal_break", "macro_part", "assembly", "reveal"),
               ("question", "hand_demo", "detail", "scale_compare", "score")),
              ("package_asmr", "snap", "plastic_detail", "reveal_hit")),
    "product": _p("product", (1.1, 3.0), (7.0, 12.0), ("claim", "spec", "proof", "verdict"),
                  ("cut_on_action", "match_cut", "punch"), .38,
                  "結論先行→外觀與情境→只挑關鍵規格→真實測試→限制→適合誰；規格不能代替證據",
                  "第一鏡先給測試結果或產品解決的真問題",
                  (("result", "product_context", "feature_action", "measurement", "limitation", "verdict"),
                   ("problem", "setup", "test_a", "test_b", "comparison")),
                  ("button_click", "material_touch", "mechanical_detail", "proof_tick")),
    "game": _p("game", (.6, 2.0), (5.0, 8.0), ("impact", "stat", "tip", "versus"),
               ("impact_cut", "glitch_once", "punch"), .60,
               "爆點複製到片頭→補最短前因→操作／選擇→impact 秒收→反應；UI 不遮 HUD",
               "第一鏡先給勝負、失誤或最強 impact",
               (("impact", "micro_context", "input", "consequence", "reaction"),
                ("challenge", "attempt", "failure", "adapt", "win")),
               ("gameplay_transient", "impact", "reaction", "music_drop")),
    "diy": _p("diy", (1.0, 3.0), (7.0, 12.0), ("materials", "steps", "warning", "result"),
              ("match_cut", "speed_ramp", "cut_on_action"), .40,
              "成品先行→before→材料→縮時骨架＋原速關鍵手勢→失敗／修正→after",
              "第一鏡先看改造後成品或最大反差",
              (("after", "before", "materials", "action_close", "checkpoint", "after"),
               ("problem", "attempt", "mistake", "fix", "proof")),
              ("tool_foley", "material_contact", "room_tone", "completion_hit")),
    "cafe": _p("cafe", (2.0, 5.0), (12.0, 20.0), ("menu", "texture", "note", "verdict"),
               ("cut", "match_motion", "dissolve_short"), .16,
               "空間呼吸→沖煮／切甜點→質地微距→飲用→安靜收尾；不為了快而破壞氛圍",
               "第一鏡先給最有氣味感的動作或空間光影",
               (("quiet_hook", "space", "hand_ritual", "texture", "sip", "hold"),
                ("exterior", "entry", "menu", "craft", "seat_view")),
               ("pour", "cup_contact", "steam", "quiet_room")),
    "documentary": _p("documentary", (2.5, 6.5), (15.0, 28.0), ("context", "quote", "evidence", "turn"),
                      ("cut", "audio_bridge", "graphic_match"), .18,
                      "人的行動／後果先行→環境脈絡→觀察細節→證詞→證據→回到人的反應",
                      "第一鏡先給會改變觀眾理解的行動或後果",
                      (("consequence", "place", "person", "observed_action", "detail", "reaction"),
                       ("question", "archive", "evidence", "counterpoint", "human_cost")),
                      ("production_sound", "room_tone", "archive_texture", "restrained_score")),
    "interview": _p("interview", (2.8, 7.0), (14.0, 24.0), ("quote", "context", "chapter", "takeaway"),
                    ("l_cut", "j_cut", "graphic_match"), .14,
                    "最強一句＋真 proof 冷開→H/G 聲音身份→回答主幹→真操作／手部／環境／文件→停頓→可執行結論；全程 no-face，不要每句 jump cut",
                    "第一鏡先聽最有代價、衝突或反差的一句，同時看可驗證結果",
                    (("proof_cold_quote", "speaker_mark", "approved_source", "screen_demo", "process_broll"),
                     ("question", "answer", "hands", "environment", "document", "takeaway")),
                    ("clean_dialogue", "room_tone", "breath", "subtle_music"),
                    direction="用 J/L cut 與資訊層更新接鏡；禁人物臉、AI 頭像、剪影與 reaction face"),
    "automotive": _p("automotive", (.8, 2.8), (6.0, 11.0), ("route", "spec", "telemetry", "verdict"),
                     ("match_motion", "speed_ramp", "cut_on_action"), .46,
                     "引擎／動態先行→車身建立→操作細節→速度段→慢下觀察→彎後 payoff；方向必連續",
                     "第一鏡先用聲音與動態兌現速度感",
                     (("engine_hook", "vehicle_wide", "control_detail", "moving_pov", "pass_by", "reaction"),
                      ("route", "setup", "acceleration", "corner", "exit", "telemetry")),
                     ("engine", "wind", "gear_change", "tire", "pass_by")),
    "fitness": _p("fitness", (.7, 2.5), (6.0, 10.0), ("goal", "form", "rep", "result"),
                  ("cut_on_action", "impact_cut", "match_motion"), .44,
                  "完成動作先行→目標→準備→動作分解→疲勞反應→最後一組；剪點跟呼吸與落地",
                  "第一鏡先看最好的一次動作或結果",
                  (("best_rep", "goal", "setup", "wide_form", "detail_form", "effort", "finish"),
                   ("before", "drill", "mistake", "correction", "after")),
                  ("breath", "foot_contact", "equipment", "effort", "impact")),
    "fashion": _p("fashion", (1.2, 3.8), (9.0, 15.0), ("look", "detail", "material", "verdict"),
                  ("match_pose", "match_motion", "cut"), .22,
                  "完整造型先行→輪廓→材質細節→穿著動作→前後對比；用姿勢／形狀接鏡，不亂甩轉場",
                  "第一鏡先給完成 look 或最強輪廓",
                  (("hero_look", "full_body", "fabric_detail", "movement", "accessory", "final_pose"),
                   ("before", "item", "layering", "match_pose", "after")),
                  ("fabric", "footstep", "accessory", "restrained_beat")),
    "architecture": _p("architecture", (2.5, 6.0), (14.0, 24.0), ("location", "plan", "material", "idea"),
                       ("graphic_match", "match_direction", "cut"), .12,
                       "外部脈絡→入口→空間序列→人作比例尺→材質／光→設計理由；鏡頭要讓觀眾認路",
                       "第一鏡先給空間最核心的光、尺度或轉折",
                       (("hero_space", "exterior", "entry", "wide", "human_scale", "material", "light"),
                        ("plan", "threshold", "circulation", "detail", "use_case")),
                       ("space_tone", "footstep", "door", "city_bed")),
    "business": _p("business", (2.0, 5.2), (10.0, 18.0), ("claim", "metric", "framework", "decision"),
                   ("cut", "data_wipe", "punch"), .24,
                   "反直覺結論→問題成本→案例→真數字→決策框架→限制；圖表只演一個關係",
                   "第一鏡先給決策後果、數字反差或錯誤共識",
                   (("result", "problem", "case", "metric", "decision", "constraint"),
                    ("claim", "evidence", "counterexample", "framework", "action")),
                   ("clean_voice", "paper_detail", "data_tick", "low_pulse")),
    "nature": _p("nature", (2.0, 6.0), (12.0, 22.0), ("species", "behavior", "fact", "turn"),
                 ("cut", "l_cut", "match_action"), .14,
                 "動物正在做事→環境→個體目標→等待→行為轉折→結果；現場聲比裝飾音效重要",
                 "第一鏡先給主角正在做選擇或遇到問題",
                 (("behavior_hook", "habitat", "subject", "goal", "patient_observation", "turn", "result"),
                  ("detail", "wide_context", "interaction", "reaction", "quiet_hold")),
                 ("wild_track", "movement_detail", "wind", "water", "bird_call")),
    "music": _p("music", (.6, 2.8), (5.0, 10.0), ("lyric", "section", "artist", "moment"),
                ("cut_on_beat", "match_motion", "phrase_cut"), .30,
                "先給副歌／最強動作→全景定場→主表演者→樂器／手部→觀眾反應；以樂句而非每拍切",
                "第一鏡先給歌曲或表演最有辨識度的一拍",
                (("peak", "stage_wide", "lead", "instrument_detail", "audience", "return_to_lead"),
                 ("phrase_start", "movement", "reaction", "phrase_end", "breath")),
                ("performance_mix", "crowd", "instrument", "stage_ambience")),
    "general": _p("general", (1.6, 4.0), (9.0, 16.0), ("chapter", "question", "recap", "proof"),
                  ("cut", "match_motion", "wipe"), .26,
                  "結果先行→脈絡→行動→轉折→短暫呼吸→payoff；每個畫面回答當下那句話",
                  "第一鏡先兌現標題承諾，不播 logo 前奏",
                  (("result", "context", "action", "detail", "reaction"),
                   ("question", "attempt", "turn", "proof", "resolve")),
                  ("production_sound", "room_tone", "foley", "music")),
}


SEMANTIC_CARDS = (
    (("為什麼", "但是", "問題", "真的嗎", "竟然", "沒想到"), "question"),
    (("步驟", "首先", "接著", "最後", "怎麼做"), "steps"),
    (("價格", "元", "$", "只要", "成本"), "price"),
    (("結果", "數據", "%", "倍", "成長", "下降", "提升"), "metric"),
    (("證明", "測試", "實測", "證據", "比較"), "proof"),
    (("警告", "注意", "不要", "失敗", "錯誤"), "warning"),
    (("地點", "地址", "路線", "位於", "抵達"), "location"),
    (("重點", "記住", "結論", "所以", "適合"), "recap"),
)
